pipe - add input from Stdin
zricethezav/gitleaks pull request #971
Opened 2022-08-31 21:17 UTC by rommi4

### Description:

with some copy-paste added pipe:
https://github.com/zricethezav/gitleaks/issues/836

usage example:
```
curl -sS -H "Accept: application/vnd.github.patch"  \
         -H "Authorization: Bearer ${TOKEN}" \
          https://api.github.com/repos/${OWNER}/${REPO}/compare/${BASE_REF}...${HEAD_REF}  | \
  ./gitleaks detect --pipe 
```
or
```
git log -p "${BASE_REF}...${HEAD_REF}" |  ./gitleaks detect --pipe
```

### Checklist:

* [x] Does your PR pass tests?
* [ ] Have you written new tests for your changes?
* [x] Have you lint your code locally prior to submission?

2022-09-01 12:42 UTC, zricethezav commented
Thanks for the PR @rommi4! 

I want the `--pipe` option to be `git` agnostic. I.e, `--pipe` should be able to accept _any_ input, not just git diffs. This is useful for streaming applications and building services around gitleaks. That said, I think there is some value in your implementation of `FromPipe` in `git/git.go`. There could be some code that quickly checks the format of stdin which would either route the detection to `gitdiff.Parse(cmd, stdout)` or straight to `detect.DetectReader` (to be implemented).

Does that make sense? It's a bit early in the morning but I can provide some more context later with what I'm looking for for this feature

2022-09-19 13:28 UTC, rommi4 commented
Hello, @zricethezav

Just updated my PR

There's simple check for [git input.](https://github.com/zricethezav/gitleaks/pull/971/files#diff-843a307bde5ddd61294c58685e121707f08adfacc34e49f7399cfc6e42e57947R368)
If git, proceed to `detect.DetectPipeGit`

`detect.DetectPipe` may be updated in future with parsers other than git
---
Already working from my fork for 2 weeks this way:
```
curl -sS  https://api.github.com/repos/${OWNER}/${REPO}/compare/${BASE_REF}...${HEAD_REF}  | ./gitleaks detect --pipe
```
suitable for checking pull requests in LARGE repos without checkout in Github Actions every time.

2022-10-18 15:17 UTC, weineran requested changes
General comment: Is it possible to unit test any of the new functionality?

Some specific comments in the code...

2022-10-18 15:17 UTC, weineran commented on detect/detect.go
> +		DetectReader = "git"
Does it make sense to move the d.DetectPipeGit call up here and remove the switch statement below?

Also, consider adding a Debug log (or Info?) saying that the input was inferred to be a git diff and will be scanned as such.

2022-10-18 15:17 UTC, weineran commented on detect/detect.go
> +		DetectReader = "unknown"
If it's not "git" does it make sense to just treat the input as a file and scan it? Not sure how complex that is, so if you think that should be deferred for future work, that's fine.

2022-10-18 15:17 UTC, weineran commented on cmd/detect.go
> +	}
It looks like this duplicates lines 113-116?

2022-10-20 09:21 UTC, rommi4 commented
may be closed because of https://github.com/zricethezav/gitleaks/pull/1012

2022-10-20 09:21 UTC, closed without merging

2022-10-20 13:11 UTC, weineran commented
@rommi4 Does #1012 meet your requirements as well?

2022-10-20 13:17 UTC, rommi4 commented
Testing at the moment. Will update if find anything